# Generated by Django 3.2.9 on 2021-11-02 14:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='creation_date',
        ),
    ]
